import { chromium } from 'playwright-core';
const SHOTS = process.env.SHOTS_DIR || 'shots';
const browser = await chromium.launch({ channel: 'msedge', headless: true, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
await page.goto('http://localhost:5174/?nosplash', { waitUntil: 'networkidle' });
await page.waitForTimeout(3000);
await page.screenshot({ path: `${SHOTS}/t-light-hero.png` });
const H = await page.evaluate(() => document.getElementById('journey').offsetHeight - window.innerHeight);
await page.evaluate((v) => window.scrollTo(0, v), H * 0.12);
await page.waitForTimeout(1600);
await page.screenshot({ path: `${SHOTS}/t-light-ruido.png` });
await page.click('#theme');
await page.waitForTimeout(800);
await page.screenshot({ path: `${SHOTS}/t-dark-ruido.png` });
await page.click('#lang2');
await page.waitForTimeout(600);
await page.evaluate(() => window.scrollTo(0, 0));
await page.waitForTimeout(1500);
await page.screenshot({ path: `${SHOTS}/t-dark-hero-en.png` });
await page.evaluate((v) => window.scrollTo(0, v), H * 0.41);
await page.waitForTimeout(1800);
await page.screenshot({ path: `${SHOTS}/t-dark-work.png` });
await page.evaluate((v) => window.scrollTo(0, v), H * 0.99);
await page.waitForTimeout(1800);
await page.screenshot({ path: `${SHOTS}/t-dark-contact.png` });
await browser.close();
